### ISSUE TITLE
Git/GitHubリソース選択

### ISSUE THREAD

**Issue by naztshinozaki** [techrisenepal/corporate#2]
* 網羅的で基本となるオンライーンリソースの選択

**Comment by AtsukiTak** [comment]
公式が一番網羅的でわかりやすいと思う。
https://git-scm.com/doc

**Comment by koka831** [comment]
## for tutorial
[link](https://guides.github.com/activities/hello-world/)
[link](http://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)
[book](https://git-scm.com/book/en/v2/)
## good txt
[link](http://rogerdudler.github.io/git-guide/)
[link](http://blog.udacity.com/2015/06/a-beginners-git-github-tutorial.html)

**Comment by AtsukiTak** [comment]
git-scm.comのやつとか"Pro Git"は網羅的だけどbeginner向けじゃないか
referenceとして紹介する感じかな

**Comment by AtsukiTak** [comment]
http://qiita.com/suin/items/06f732b1597405e9547d

**Comment by AtsukiTak** [comment]
正直どれもGitとGitHubの切り分けできてなかったり、動けばいいっしょ的な思想がチラチラ見えたりで自分好みでなかったので、基本的に自分で書くことにしました
